---
name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: |
      Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

- type: textarea
  id: summary
  attributes:
    label: Feature Summary
    description: A brief description of the feature you'd like to see.
    placeholder: What feature would you like to see added?
  validations:
    required: true

- type: textarea
  id: problem
  attributes:
    label: Problem/Use Case
    description: What problem would this feature solve? What's your use case?
    placeholder: Describe the problem this feature would solve...
  validations:
    required: true

- type: textarea
  id: solution
  attributes:
    label: Proposed Solution
    description: How would you like this feature to work?
    placeholder: Describe how you think this feature should work...

- type: textarea
  id: alternatives
  attributes:
    label: Alternative Solutions
    description: Have you considered any alternative solutions?
    placeholder: Any other ways to solve this problem?

- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: Add any other context, screenshots, or examples.
    placeholder: Any additional information?

- type: checkboxes
  id: checklist
  attributes:
    label: Checklist
    description: Please check the following before submitting
    options:
      - label: This feature doesn't already exist
        required: true
      - label: I have searched for similar feature requests
        required: true